import { NotFoundError, ValidationError } from "../utils/customErrors.js";
import BaseModel from "./base/BaseModel.js";
import { pipe, curry, pick, omit } from "../utils/functional.js";
import { generateUuidV4 } from "../utils/uuid.js";
import { validateUserForContext } from "../utils/validationSchemas.js";

import hashing from "../utils/hashing.js";

/**
 * User Model - Functional + OOP Hybrid
 * Extends BaseModel to inherit common functionality and validation
 */
export class User extends BaseModel {
   constructor(
      id = null,
      name,
      role,
      email,
      password = null,
      passwordHash = null
   ) {
      super(); // Initialize BaseModel (sets up _errors and _isValid)

      if (id) {
         this.id = id;
      } else {
         try {
            this.id = generateUuidV4();
            // console.log(`[User CONSTRUCTOR DEBUG] Generated new ID: ${this.id} (type: ${typeof this.id})`); // Temporary detailed log
            if (
               !this.id ||
               typeof this.id !== "string" ||
               this.id.length < 36
            ) {
               // Basic check for UUID format (e.g., length)
               console.error(
                  `[USER_MODEL_CONSTRUCTOR_ERROR] Invalid or missing UUID generated by generateUuidV4(). Value: '${
                     this.id
                  }', Type: ${typeof this
                     .id}. This will likely cause a DB error.`
               );
               // Fallback or error throw strategy could be implemented here if critical
               // For now, if generateUuidV4 fails, this.id might remain undefined or problematic
            }
         } catch (e) {
            console.error(
               "[USER_MODEL_CONSTRUCTOR_ERROR] Error during generateUuidV4() call:",
               e
            );
            // Decide on fallback if uuid generation itself throws an error
            this.id = null; // Ensure id is explicitly null if generation fails catastrophically
         }
      }

      this.name = name;
      this.role = role;
      this.email = email;
      this.password = password;

      // Handle password hashing
      if (passwordHash) {
         this.passwordHash = passwordHash;
      } else if (password) {
         this.passwordHash = hashing.hash(password);
      }

      // Run validation on construction
      this.validate();
   }

   /**
    * Validate user instance
    * Uses methods from ValidationMixin via BaseModel
    */
   validate() {
      this.clearErrors();

      // Determine if this is a lookup context (e.g., only id or only email is primarily set for lookup)
      const isLookupContext =
         (this.id &&
            !this.name &&
            !this.email &&
            !this.role &&
            !this.password &&
            !this.passwordHash) ||
         (!this.id &&
            this.email &&
            !this.name &&
            !this.role &&
            !this.password &&
            !this.passwordHash);

      // Required fields validation - more lenient in lookup context
      if (!isLookupContext) {
         this.validateRequired(["name", "email", "role"]);
      }

      // Name validation according to OpenAPI spec
      if (this.name && !isLookupContext) {
         // Pattern: letters and spaces. Original spec comment: only letters (^[a-zA-Z]+$)
         if (!/^[a-zA-Z ]+$/.test(this.name)) {
            // Allow spaces
            this.addError("Name must contain only letters and spaces", "name"); // Update error message
         }
         // Length: 3-50 characters
         if (!User.validateStringLength(this.name, 3, 50)) {
            this.addError("Name must be between 3 and 50 characters", "name");
         }
      }

      // Email validation according to OpenAPI spec
      if (this.email) {
         if (!User.isValidEmail(this.email)) {
            this.addError("Invalid email format", "email");
         }
         // Max length: 50 characters
         if (this.email.length > 50) {
            this.addError("Email must not exceed 50 characters", "email");
         }
      }

      // Role validation according to OpenAPI spec: [user, admin, owner] only
      if (
         !isLookupContext &&
         this.role &&
         !["user", "admin", "owner"].includes(this.role)
      ) {
         this.addError("Invalid role. Must be: user, admin, or owner", "role");
      }

      // Password validation according to OpenAPI spec
      if (!isLookupContext && this.password && !this.passwordHash) {
         // Length: 8-100 characters
         if (this.password.length < 8 || this.password.length > 100) {
            this.addError(
               "Password must be between 8 and 100 characters",
               "password"
            );
         }

         // const passwordValidation = User.validatePasswordStrength(
         //    this.password
         // );
         // if (!passwordValidation.valid) {
         //    this.addError(passwordValidation.error, "password");
         // }
      }

      return this;
   }

   // --- PURE FACTORY FUNCTIONS ---

   /**
    * Create user from credentials (typically from registration)
    */
   static fromCredentials = (credentials) => {
      const user = new User(
         null,
         credentials.name,
         credentials.role || "user",
         credentials.email,
         credentials.password
      );

      if (!user.isValid()) {
         throw new ValidationError("Invalid user data", user.getErrors());
      }

      return user;
   };
   /**
    * Create user from request body (used by service pipeline)
    * @param {Object} requestBody - Request body or user data
    * @returns {User} User instance
    */
   static fromRequestBody = (requestBody) => {
      console.log(
         "User.fromRequestBody received:",
         JSON.stringify(requestBody, null, 2)
      ); // Temporary debug log for MCP tool issue

      // Ensure body is an object, and try to get schema from it or the parent requestBody
      const rawBody = requestBody ? requestBody.body || requestBody : {};
      const schema = rawBody.schema || (requestBody && requestBody.schema); // Get schema if present directly on data or parent

      let processedBody = rawBody;

      // If schema is available, perform context-specific validation first.
      // validateUserForContext will throw ValidationError if rules are not met.
      if (schema) {
         console.log(
            `User.fromRequestBody: Schema detected ('${schema}'), applying context-specific validation.`
         );
         processedBody = validateUserForContext(schema, rawBody);
         // validateUserForContext returns the data, possibly transformed or validated.
         // We should use this processedBody for User instantiation.
      }

      const user = new User(
         processedBody.id || null,
         processedBody.name || null,
         processedBody.role || "user", // Default role assignment
         processedBody.email || null,
         processedBody.password || null,
         processedBody.passwordHash || processedBody.password_hash || null // Support both formats for compatibility
      );

      // Determine if this is a lookup context based on the state of processedBody AFTER potential validation
      const isLookupContext =
         (processedBody.id &&
            !processedBody.name &&
            !processedBody.email &&
            !processedBody.role) ||
         (!processedBody.id &&
            processedBody.email &&
            !processedBody.name &&
            !processedBody.role);

      // This final validation check remains.
      // If validateUserForContext ran, user.isValid() (generic User.validate()) should pass for common fields.
      // If no schema was provided, this is the primary validation point after construction.
      if (!user.isValid() && !isLookupContext) {
         console.warn(
            `User.fromRequestBody: User instance is invalid after construction (schema: ${
               schema || "N/A"
            }). Errors:`,
            user.getErrors()
         );
         throw new ValidationError(
            "Invalid user data for the given operation (User.fromRequestBody)",
            user.getErrors()
         );
      }

      return user;
   };
   /**
    * Create user from database row
    * @param {Object} dbRow - Database row
    * @returns {User} User instance
    */
   static fromDb = (dbRow) => {
      if (!dbRow) {
         throw new NotFoundError("User not found or access denied");
      }

      return new User(
         dbRow.id,
         dbRow.name,
         dbRow.role,
         dbRow.email,
         null, // dbRow.password is usually null from DB
         dbRow.password_hash // Use password_hash from DB directly here
      );
   };

   /**
    * Create user for authentication check
    */
   static forAuth = (email, plainPassword) => {
      const user = new User(null, null, "user", email, plainPassword);
      // Clear validation errors since we only need email/password for auth
      user.clearErrors();
      return user;
   };

   // --- IMMUTABLE TRANSFORMATION METHODS ---

   /**
    * Return new user instance with updated role
    * @param {string} newRole - New role
    * @returns {User} New user instance
    */
   withRole = (newRole) => {
      return new User(
         this.id,
         this.name,
         newRole,
         this.email,
         null,
         this.passwordHash
      );
   };

   /**
    * Return new user instance with updated name
    * @param {string} newName - New name
    * @returns {User} New user instance
    */
   withName = (newName) => {
      return new User(
         this.id,
         newName,
         this.role,
         this.email,
         null,
         this.passwordHash
      );
   };

   /**
    * Return new user instance with updated email
    * @param {string} newEmail - New email
    * @returns {User} New user instance
    */
   withEmail = (newEmail) => {
      return new User(
         this.id,
         this.name,
         this.role,
         newEmail,
         null,
         this.passwordHash
      );
   };

   /**
    * Return new user instance with new password
    * @param {string} newPassword - New plain password
    * @returns {User} New user instance with hashed password
    */
   withPassword = (newPassword) => {
      return new User(
         this.id,
         this.name,
         this.role,
         this.email,
         newPassword, // Will be hashed in constructor
         null
      );
   };

   // --- PURE DATA TRANSFORMERS ---

   static update(requestBody, existingUser) {
      if (!existingUser) {
         throw new ValidationError("User not found");
      }

      const allowedUpdates = ["name", "role"];

      const updateKeys = Object.keys(requestBody).filter((key) =>
         allowedUpdates.includes(key)
      );

      const updateData = Object.fromEntries(
         updateKeys.map((key) => [key, requestBody[key]])
      );

      return new User(
         existingUser.id,
         updateData.name || existingUser.name,
         updateData.role || existingUser.role,
         existingUser.email, // email should not be updated here usually
         null, // password not updated here
         existingUser.passwordHash
      );
   }

   /**
    * Convert to database-ready object (without plain secret)
    * @returns {Object} Object ready for database insertion
    */
   toDatabaseObject = () => {
      const dbObject = {
         id: this.id,
         name: this.name,
         role: this.role,
         email: this.email,
         password_hash: this.passwordHash,
      };
      return dbObject;
   };

   /**
    * Convert to database parameter array
    * @returns {Array} Array ready for parameterized queries
    */
   toDatabaseArray = () => [
      this.id,
      this.name,
      this.role,
      this.email,
      this.passwordHash,
   ];

   /**
    * Convert to safe API response (overrides BaseModel method)
    * @returns {Object} User object without sensitive data
    */
   toApiResponse = () => ({
      id: this.id,
      name: this.name,
      role: this.role,
      email: this.email,
   });

   /**
    * Convert to JWT payload
    * @returns {Object} User data for JWT token
    */
   toJwtPayload = () => ({
      id: this.id,
      email: this.email,
      role: this.role,
   });

   // --- PURE PREDICATES ---

   /**
    * Check if user has a specific role
    * @param {string} requiredRole - Role to check
    * @returns {boolean}
    */
   hasRole = (requiredRole) => this.role === requiredRole;

   /**
    * Check if user is admin or owner
    * @returns {boolean}
    */
   isPrivileged = () => this.role === "admin" || this.role === "owner";

   /**
    * Check if user can manage another user
    * @param {User} otherUser - User to check against
    * @returns {boolean}
    */
   canManage = (otherUser) => {
      if (this.role === "owner") return true;
      if (this.role === "admin" && otherUser.role === "user") return true;
      return this.id === otherUser.id;
   };

   /**
    * Verify password against hash
    * @param {string} plainPassword - Plain password to verify
    * @returns {boolean}
    */
   verifyPassword = (plainPassword) => {
      if (!this.passwordHash) return false;
      return hashing.same(plainPassword, this.passwordHash);
   };

   /**
    * Alternative validation approach using validation rules
    * Example of how to use the comprehensive validation system
    */
   static getValidationRules() {
      return [
         {
            field: "email",
            validators: [
               (value) =>
                  value
                     ? { valid: true }
                     : { valid: false, error: "Email is required" },
               (value) =>
                  User.isValidEmail(value)
                     ? { valid: true }
                     : { valid: false, error: "Invalid email format" },
            ],
         },
         {
            field: "name",
            validators: [
               (value) =>
                  value
                     ? { valid: true }
                     : { valid: false, error: "Name is required" },
               (value) =>
                  User.validateStringLength(value, 1, 50)
                     ? { valid: true }
                     : {
                          valid: false,
                          error: "Name must be between 1 and 50 characters",
                       },
            ],
         },
         {
            field: "role",
            validators: [
               (value) =>
                  User.isValidRole(value)
                     ? { valid: true }
                     : { valid: false, error: "Invalid role" },
            ],
         },
      ];
   }
}

// Copy static methods from BaseModel to User (to ensure ValidationMixin methods are available)
Object.getOwnPropertyNames(BaseModel).forEach((name) => {
   if (
      name !== "prototype" &&
      name !== "length" &&
      name !== "name" &&
      !(name in User)
   ) {
      User[name] = BaseModel[name];
   }
});
